<a href="https://colab.research.google.com/github/ArhaanAli04/Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(1)

2.5.1+cu121
1


In [ ]:
print("arhaan")
import torch
print(torch.__version__)

arhaan
2.5.1+cu121


In [ ]:
#intro to tensors
#scalar
scalar=torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim
#dimension of scalar is 0, just a number

0

In [ ]:
#get tensor back as python integer
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([3,3])
vector

tensor([3, 3])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX=torch.tensor([ [1,2],
                      [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:

print(MATRIX[0])# 1st dimension
print(MATRIX[1])# 2nd dimension

tensor([1, 2])
tensor([3, 4])


In [ ]:
#tensors
TENSOR=torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR.ndim

3

In [ ]:
scalar1=torch.tensor(20)
scalar1

tensor(20)

###Random Tensors


In [ ]:
#create a random tensor:
import torch
random_tensor=torch.rand(4,4)
random_tensor

tensor([[0.0253, 0.2150, 0.7354, 0.5163],
        [0.9605, 0.5979, 0.0950, 0.8174],
        [0.0148, 0.6786, 0.3981, 0.0895],
        [0.2887, 0.1045, 0.3069, 0.0922]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones


In [ ]:
#create a tensor of all zeros:
zeros=torch.zeros(size=(4,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones:
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Creating a range of tensors and tensors-like

In [ ]:
#use torch.arange():
one_to_ten=torch.arange(start=10,end=100,step=6)
one_to_ten

tensor([10, 16, 22, 28, 34, 40, 46, 52, 58, 64, 70, 76, 82, 88, 94])

In [ ]:
#creating tensors like:
torch.zeros_like(input=one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Getting information from tensors

In [ ]:
import torch
tensor1=torch.rand(3,4,dtype=torch.float16)
tensor1

tensor([[0.1616, 0.3701, 0.4136, 0.3716],
        [0.0518, 0.7158, 0.8755, 0.4194],
        [0.1611, 0.6870, 0.6440, 0.8428]], dtype=torch.float16)

In [ ]:
print(f"Datatype of tensor: {tensor1.dtype}")
print(f"Shape of tensor: {tensor1.shape}")
print(f"Device tensor is on: {tensor1.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating tensors(tensor operations):
* addition
* subtraction
* multiplication(element-wise)
* division
* matrix multiplication

In [ ]:
tensor=torch.tensor([2,3,4])
tensor+20

tensor([22, 23, 24])

In [ ]:
tensor-10

tensor([-8, -7, -6])

In [ ]:
tensor*10

tensor([20, 30, 40])

In [ ]:
#use pytorch inbuilt modules

print(torch.mul(tensor,10))
print(torch.add(tensor,20))
print(10)

tensor([20, 30, 40])
tensor([22, 23, 24])
10


In [ ]:
#element wise multiplication:
print(tensor)
print(tensor*tensor)
#matrix multiplication:
print(torch.matmul(tensor,tensor))

tensor([2, 3, 4])
tensor([ 4,  9, 16])
tensor(29)


In [ ]:
tensorA=torch.rand(3,2)
tensorB=torch.rand(2,3)
print(tensorA)
print(tensorB)
print(torch.matmul(tensorA,tensorB))
print(tensorA.T)

tensor([[0.8201, 0.7973],
        [0.1552, 0.6626],
        [0.3609, 0.5074]])
tensor([[0.7840, 0.6838, 0.4390],
        [0.5197, 0.7420, 0.0015]])
tensor([[1.0573, 1.1523, 0.3613],
        [0.4660, 0.5977, 0.0691],
        [0.5466, 0.6232, 0.1592]])
tensor([[0.8201, 0.1552, 0.3609],
        [0.7973, 0.6626, 0.5074]])


In [ ]:
torch.matmul(tensorA,tensorA.T)

tensor([[1.3083, 0.6556, 0.7005],
        [0.6556, 0.4631, 0.3922],
        [0.7005, 0.3922, 0.3877]])

###Tensor Aggregation(min,max,mean,sum)

In [ ]:

x=torch.arange(0,20,2)
print(x)

print(f"Min: {torch.min(x)}") #min
print(f"Max: {torch.max(x)}") #max
print(f"Mean: {torch.mean(x.type(torch.float32))}") #mean
print(f"Sum: {torch.sum(x)}")  #sum

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
Min: 0
Max: 18
Mean: 9.0
Sum: 90


###Positional Min and Max

In [ ]:
print(x.argmin())
print(x.argmax())
print(5)

tensor(0)
tensor(9)
5


###Reshaping,Viewing,Stacking,Squeezing a tensor

In [ ]:
import torch
x=torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
#adding a dimension
x_reshaped=x.reshape(1,10)
x_reshaped,x_reshaped.shape,x_reshaped.ndim

(tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]), 2)

In [ ]:
#changing the view of a tensor
z=x.view(1,10)
z,z.shape


(tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
#changing z will change x:
z[:,0]=50
z,x

(tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([50,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
#stack tensor :
x_stacked=torch.stack([x,x,x], dim=0)
x_stacked

tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [50,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [50,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
#squeezing a tensor
x_reshaped,x_reshaped.shape

(tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")
x_squeezed=x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Previous tensor shape: torch.Size([1, 10])
New tensor: tensor([50,  2,  3,  4,  5,  6,  7,  8,  9, 10])
New tensor shape: torch.Size([10])


In [ ]:
#unsqueezing a tensor:
print(f"Previous tensor:{x_squeezed}")
print(f"Previous tensor shape: {x_squeezed.shape}")
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New tensor shape:{x_unsqueezed.shape}")

Previous tensor:tensor([50,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous tensor shape: torch.Size([10])
New tensor: tensor([[50,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
New tensor shape:torch.Size([1, 10])


In [ ]:
#permute:
x1=torch.rand(size=(224,224,3)) # height,width,color
x_permuted=x1.permute(2,0,1)
print(f"Previous shape: {x1.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing (selecting fata from tensors)

In [ ]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(f"x[0]:{x[0]}")
print(f"x[0][0]: {x[0][0]}   x[0][1]:{x[0][1]}   x[0][2]:{x[0][2]}")
x[0][2][1]

x[0]:tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x[0][0]: tensor([1, 2, 3])   x[0][1]:tensor([4, 5, 6])   x[0][2]:tensor([7, 8, 9])


tensor(8)

In [ ]:
#use : to select all of a target dimension
print(f"x[:,0]={x[:,0]}   x[:,1]={x[:,1]}   x[:,2]={x[:,2]}")  #rows
print(f"x[:,:,0]={x[:,:,0]}   x[:,:,1]={x[:,:,1]}    x[:,:,2]={x[:,:,2]}")  #columns


x[:,0]=tensor([[1, 2, 3]])   x[:,1]=tensor([[4, 5, 6]])   x[:,2]=tensor([[7, 8, 9]])
x[:,:,0]=tensor([[1, 4, 7]])   x[:,:,1]=tensor([[2, 5, 8]])    x[:,:,2]=tensor([[3, 6, 9]])
tensor([1])


In [ ]:
x[:,2,:], x[:,2]

(tensor([[7, 8, 9]]), tensor([[7, 8, 9]]))

##Reproducibility

In [ ]:
import torch
  #create 2 random tensors
random_tensorA=torch.rand(3,4)
random_tensorB=torch.rand(3,4)
print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)

tensor([[0.5711, 0.7145, 0.6527, 0.6038],
        [0.2189, 0.4920, 0.3929, 0.8372],
        [0.0181, 0.3447, 0.3640, 0.3066]])
tensor([[0.1344, 0.3948, 0.7411, 0.7791],
        [0.1363, 0.0076, 0.5684, 0.0019],
        [0.7075, 0.2676, 0.0427, 0.8220]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#making random reproducible tensors
#set random seed
random_seed=50
torch.manual_seed(random_seed)
random_tensorC=torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensorD=torch.rand(3,4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC==random_tensorD)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])
tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
print(1)

1
